"""Risk Pulse router — exposes alert queue and manual trigger."""
from __future__ import annotations

from fastapi import APIRouter, Query
from fastapi.responses import JSONResponse

from agents.risk_pulse import get_alerts, inject_demo_alerts

router = APIRouter(prefix="/risk-pulse", tags=["Risk Pulse"])


@router.get("", summary="Get current risk pulse alerts")
async def get_risk_alerts(
    limit: int = Query(20, ge=1, le=100, description="Max alerts to return"),
) -> JSONResponse:
    """
    Returns the latest risk alerts generated by the background pulse scan.
    Alerts are sorted newest-first.

    Severity levels: CRITICAL | HIGH | MEDIUM | LOW
    """
    alerts = get_alerts(limit=limit)
    return JSONResponse(
        content={
            "alerts": alerts,
            "total": len(alerts),
        }
    )


@router.post("/demo", summary="Inject demo alerts (for testing)")
async def inject_demo() -> JSONResponse:
    """Populate the alert queue with realistic demo alerts without waiting 30 minutes."""
    inject_demo_alerts()
    alerts = get_alerts(limit=10)
    return JSONResponse(
        content={
            "success": True,
            "message": "Demo alerts injected.",
            "alerts": alerts,
        }
    )
